using System.Text;
using KyberWeave.Core.Configuration;

namespace KyberWeave.Core.Docs.Scaffolding;

/// <summary>
/// Renders the configuration registry as the generated region of the repository root
/// <c>AGENTS.md</c>, and splices it into a file whose other content is hand-authored.
/// </summary>
/// <remarks>
/// <para>
/// The registry's truth is <c>.kyber-weave/kyber-weave.yml</c>. This is its second audience:
/// configuration is what the CLI and MCP server read, and Markdown between markers is what an
/// agent reads. Neither has to parse the other's format, and the markers make the boundary
/// between generated and hand-authored content explicit rather than a convention someone has
/// to know.
/// </para>
/// <para>
/// The region is rewritten on every run, including without <c>--force</c>. It is generated
/// output, and a stale copy of the registry is worse than none: an agent that resolves a name
/// to a path that moved fails in a way that looks like the repository is wrong. Everything
/// outside the markers is returned byte for byte.
/// </para>
/// </remarks>
internal static class ConfigRegMarkdown
{
    public const string StartMarker = "<!-- KYBER_WEAVE_CONFIG_REG_START -->";
    public const string EndMarker = "<!-- KYBER_WEAVE_CONFIG_REG_END -->";

    /// <summary>True when <paramref name="content"/> already carries a generated region.</summary>
    public static bool ContainsBlock(string content)
    {
        ArgumentNullException.ThrowIfNull(content);
        return content.Contains(StartMarker, StringComparison.Ordinal);
    }

    /// <summary>The generated region, markers included, with <c>\n</c> line endings.</summary>
    public static string Render(IReadOnlyList<ConfigRegEntry> entries)
    {
        ArgumentNullException.ThrowIfNull(entries);

        StringBuilder builder = new StringBuilder();
        builder.Append(StartMarker).Append('\n');
        builder.Append("""
            ## Repository Configuration & Paths Registry (Config Reg)

            Agents and skills look up the following properties to find the documentation and
            references that belong to this repository.


            """);

        foreach (ConfigRegEntry entry in entries)
        {
            builder.Append("- **<").Append(entry.Name).Append(">**: `").Append(entry.Path).Append("`\n");
        }

        // The worked example names a real property rather than a literal, so renaming one
        // cannot leave this paragraph illustrating a lookup that no longer resolves.
        builder.Append($"""

            Skills and other portable instruction files SHALL reference these paths by the
            property name above — "the path declared as **<{ConfigRegConfig.ComponentCatalogProperty}>**
            in the repository root `AGENTS.md`" — rather than embedding a relative link that
            traverses out of the skill's own directory. A skill written that way stays correct
            when this repository moves something; only this registry has to change.

            Generated by `kyber-weave docs init` from `.kyber-weave/kyber-weave.yml`. Edit that
            file rather than this block: everything between the markers is rewritten on the next
            run.

            """);
        builder.Append(EndMarker).Append('\n');
        return builder.ToString();
    }

    /// <summary>
    /// Returns <paramref name="existing"/> with its generated region replaced by
    /// <paramref name="block"/>, appending the region when the file has no markers.
    /// </summary>
    public static string Splice(string existing, string block)
    {
        ArgumentNullException.ThrowIfNull(existing);
        ArgumentException.ThrowIfNullOrWhiteSpace(block);

        string newline = DominantNewline(existing);
        List<string> lines = existing.Split('\n').Select(line => line.TrimEnd('\r')).ToList();
        List<string> replacement = block.TrimEnd('\n').Split('\n').ToList();

        int start = lines.FindIndex(line => line.Trim() == StartMarker);
        if (start < 0)
            return string.Join(newline, Append(lines, replacement));

        int end = lines.FindIndex(start + 1, line => line.Trim() == EndMarker);
        if (end < 0)
        {
            // Replacing to end of file would delete whatever the operator wrote below an
            // unclosed marker. Which content that is cannot be known here, so this stops.
            throw new InvalidDataException(
                $"AGENTS.md opens a Config Reg block with {StartMarker} but never closes it " +
                $"with {EndMarker}. Close the block, or delete the opening marker, and re-run.");
        }

        lines.RemoveRange(start, end - start + 1);
        lines.InsertRange(start, replacement);
        return string.Join(newline, lines);
    }

    /// <summary>The whole file for a repository that had no <c>AGENTS.md</c> at all.</summary>
    public static string NewAgentsFile(string block, string docsRoot)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(block);
        ArgumentException.ThrowIfNullOrWhiteSpace(docsRoot);

        return $"""
        # Working in this repository

        Instructions for agents working here. Everything outside the generated block below is
        yours to write: what this repository is, the commands that must pass before a change
        lands, and the conventions worth stating.

        Documentation lives in [`{docsRoot}/`]({docsRoot}/README.md).

        {block}
        """;
    }

    private static List<string> Append(List<string> lines, List<string> replacement)
    {
        // A file that does not end in a blank line would otherwise absorb the marker into its
        // last paragraph, which changes how the Markdown renders as well as how it reads.
        while (lines.Count > 0 && lines[^1].Trim().Length == 0)
            lines.RemoveAt(lines.Count - 1);

        if (lines.Count > 0)
            lines.Add(string.Empty);

        lines.AddRange(replacement);
        lines.Add(string.Empty);
        return lines;
    }

    private static string DominantNewline(string content) =>
        content.Contains("\r\n", StringComparison.Ordinal) ? "\r\n" : "\n";
}
